{% set version = "2.3.4" %}

# Adapted from: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/structure/meta.yaml

package:
  name: 'structure'
  version: {{ version }}

source:
  md5: 620ca8a96640ff504e436a6a04efe624
  url: https://web.stanford.edu/group/pritchardlab/structure_software/release_versions/v{{ version }}/release/structure_windows_console.zip

build:
  number: 1
  # skip: True  # [not win]

test:
  commands:
    - structure | findstr /R "Version {{ version }}"

about:
  home: 'https://web.stanford.edu/group/pritchardlab/structure.html'
  license: MIT
  summary: "The program structure is a free software package for using multi-locus genotype data to investigate population structure. Its uses include inferring the presence of distinct populations, assigning individuals to populations, studying hybrid zones, identifying migrants and admixed individuals, and estimating population allele frequencies in situations where many individuals are migrants or admixed. It can be applied to most of the commonly-used genetic markers, including SNPS, microsatellites, RFLPs and AFLPs."
